::Lewd.Strings <- {};

// =============================================================================
// ALLURE EVENTS — Camp encounters with male brothers, scaled by allure stat.
// Each has reject/sub/dom structure with dom success gated by dom score.
// =============================================================================

// ---- Lingering Gaze (mild, allure 15+) ----
::Lewd.Strings.AllureGaze <- {
	Screen_A = "The campfire has burned low. Most of the brothers have turned in for the night, but %man% lingers. He sits across from you, pretending to sharpen his blade, though his hands went still some time ago. You can feel his eyes on you, tracing the line of your throat, the place where your collar gives way to skin. He is not subtle about it. He hasn't been for days.\n\nThe firelight catches on something in his expression that isn't quite respect. You've seen that look before. Hunger wrapped in the thinnest gauze of restraint. The kind of restraint that frays a little more each night.\n\nHe notices you noticing. For a moment neither of you moves.",

	Screen_Reject = "%SPEECH_ON%If you're going to stare, you'd better have something worth saying.%SPEECH_OFF%Your voice cuts across the quiet camp like a blade drawn from its sheath. %man% flinches, his eyes snapping to your face as though caught stealing. The whetstone resumes its rhythm against his sword, too quick, too loud.\n\n%SPEECH_ON%Won't happen again, captain.%SPEECH_OFF%He says it to his blade, not to you. You let the silence stretch until it says what words don't need to. Then you rise and walk to your tent without looking back.\n\nThe message lands. But as you settle into your bedroll, you wonder how many others have been watching when you weren't looking.",

	Screen_Sub = "You drop your eyes to the fire. A flush creeps up the back of your neck, and you tell yourself it's the heat from the coals. But your skin prickles with the awareness of his gaze still resting on you, heavier now that you've given ground.\n\nYou hear him shift. Leather creaking as he leans forward. Closer. The silence between you changes shape, filling with something dense and warm. He knows you noticed. He knows you chose not to stop him. That knowledge sits between you like an open door.\n\nWhen you finally stand to leave, your legs feel unsteady. You don't look at him as you pass, but you feel the heat of his attention follow you all the way to your tent. Inside, alone, your pulse takes its time settling.\n\nYou didn't say no. He'll remember that.",

	Screen_DomSuccess = "You lift your chin and meet his eyes. Not a glance. Not a warning. A challenge. You let him see that you know exactly what he's looking at, and you hold yourself perfectly still, giving him nothing to hide behind.\n\n%man%'s jaw tightens. His fingers go white around the whetstone. For a heartbeat he holds, riding the edge of something dangerous, and then his gaze breaks like a wave against stone. He looks down at his hands, at his sword, at anything that isn't you.\n\n%SPEECH_ON%Sorry, captain. I was just... thinking.%SPEECH_OFF%The apology comes rough and low, stripped of the bravado he wears in front of the other men. You let it hang in the air long enough to sting before you speak.\n\n%SPEECH_ON%Think quieter.%SPEECH_OFF%You rise and walk past him. Close enough that he can catch your scent, close enough that his breath hitches. But you don't touch him. You don't need to. The power in this exchange belongs entirely to you, and both of you know it.",

	Screen_DomFail = "You lift your chin and meet his eyes, pouring every ounce of command you can muster into the stare. For a moment it works. His hands go still on the whetstone. Something flickers in his expression. Uncertainty, maybe even deference.\n\nThen it passes. A slow smile spreads across his face, and your stomach drops. He doesn't look away. Instead he holds your gaze with a steadiness that makes your skin prickle, and you realize with a flush of heat that you are the one who wants to break first.\n\nYou do. Your eyes drop to the fire. The flush spreads from your neck to your cheeks, and you hope the firelight hides it. It doesn't. You can hear the quiet exhale of his satisfaction, barely louder than the crackle of embers.\n\n%SPEECH_ON%Sleep well, captain.%SPEECH_OFF%The title has never sounded less like respect. You retreat to your tent with your pulse hammering, acutely aware that something has shifted between you. You tried to assert yourself and lost, and that failure says more than submission ever would. You chose to fight and he won.\n\nHe'll remember that too.",
};

// ---- Uninvited Touch (medium, allure 25+, no reject option) ----
::Lewd.Strings.AllureTouch <- {
	Screen_A = "It happens during the march. The trail narrows between two ridges of mossy stone, forcing the company into single file. %man% falls in behind you, close enough that you can hear his breathing over the crunch of gravel.\n\nHis hand brushes the small of your back. Light. Brief. The kind of touch that could be accidental if you chose to believe it. You don't.\n\nThis is the third time today. The first was his shoulder against yours as you broke camp. The second was his fingers closing over yours as you both reached for the water skin, lingering a beat too long before he pulled away with a grin that didn't reach his eyes. And now this. His palm flat against the curve of your spine, separated from skin by nothing more than a thin layer of cloth.\n\nHe doesn't apologize. He doesn't pretend it was an accident. He simply waits to see what you'll do.",

	Screen_Sub = "You keep walking. Your shoulders tighten but your feet don't stop, and the hand at your back takes that for what it is. Permission. His fingers spread, pressing into the muscle along your spine, and something in your chest goes liquid and warm.\n\nThe trail opens into a clearing and the company fans out, but %man% stays close. His hand slides lower, settling at your hip with a possessiveness that sends a jolt through your belly. You can feel the other brothers glancing your way, reading the body language, filing it away. None of them say anything.\n\nAt the next rest stop, %man% sits beside you. Close. His thigh pressed against yours, one arm draped behind you in a gesture that looks casual to anyone not paying attention. But you are paying attention, and so is everyone else.\n\nYou tell yourself you'll address it later. But later keeps retreating, and his hand keeps finding reasons to touch you, and each time it does, the refusal catches in your throat a little earlier.",

	Screen_DomSuccess = "Your hand snaps back and locks around his wrist. You feel the tendons under your fingers go taut as a bowstring, and you squeeze until you feel bone. Then you twist, spinning to face him on the narrow trail.\n\nHis eyes widen. The smile dies. Up close you can see sweat beading at his temples, can smell the leather and iron and underneath it the salt of a body that wanted something it shouldn't have reached for.\n\nYou pull him close. Close enough to whisper. Close enough that his breath stutters.\n\n%SPEECH_ON%Next time, I take the hand.%SPEECH_OFF%You release him and turn back to the trail without waiting for an answer. Behind you, the silence is absolute. When the company makes camp that evening, %man% gives you a wide berth, but you catch him watching from across the fire with an expression you haven't seen on him before. Not hunger. Something closer to respect.\n\nGood.",

	Screen_DomFail = "Your hand snaps back and locks around his wrist. For one satisfying moment you feel him tense, caught off guard, and you start to twist.\n\nHe's faster. Stronger. His arm doesn't budge. Instead his free hand catches your elbow and steadies you as you stumble on the uneven trail, pulling you back against his chest in a motion that looks, to anyone watching, like he just saved you from a fall.\n\n%SPEECH_ON%Careful.%SPEECH_OFF%His voice is low, warm, almost amused. His lips are close enough to your ear that you can feel the shape of the word. His hand remains at your back, firmer now, and his grip on your wrist has shifted from defense to something gentler. Possessive.\n\nYou could struggle. Make a scene. But the company is watching, and your face is already burning, and some part of you that you'd rather not examine too closely has gone soft at the contact. You let him steady you. His thumb traces a slow circle against the inside of your wrist before he lets go.\n\n%SPEECH_ON%I've got you, captain.%SPEECH_OFF%The trail widens and he falls back to his usual position, but the ghost of his touch stays with you for miles.",
};

// ---- Night Visitor (intense, allure 35+) ----
::Lewd.Strings.AllureNight <- {
	Screen_A = "The tent flap stirs. You are not asleep. Part of you has been waiting for this, though you couldn't have said so if asked. You lie still, eyes half open in the dark, and listen to the rustle of someone slipping inside with practiced quiet.\n\nMoonlight cuts through the gap as %man% eases the flap shut behind him. He crouches at the entrance for a moment, letting his eyes adjust. When he finds you watching him, he doesn't startle. He was counting on you being awake.\n\n%SPEECH_ON%Can't sleep.%SPEECH_OFF%The lie sits between you, transparent and unashamed.\n\nHe is close enough to touch. Close enough that you can see the rapid flutter of his pulse at his throat, can hear the careful way he controls his breathing. He wants something, and the asking of it has stripped away the casual swagger he wears during the day. In the dark, without an audience, he is just a man on his knees in front of you.",

	Screen_Reject = "%SPEECH_ON%Get out.%SPEECH_OFF%Two words. Flat. Final. You don't raise your voice. You don't need to. The authority in your tone fills the small space between you like a wall.\n\n%man% freezes. You watch the struggle play across his face: desire warring with something older and deeper, the instinct that tells a soldier when they've crossed a line with their commanding officer. The instinct wins. He backs out of the tent with his palms raised, a gesture of surrender that does little to hide the state of him.\n\n%SPEECH_ON%Sorry, captain. Forget I was here.%SPEECH_OFF%The flap falls shut. You lie in the dark and listen to his retreating footsteps, your heartbeat loud in the silence he left behind.\n\nSleep comes eventually, but it is thin and restless. You dream of things you won't remember in the morning, and wake with your hand pressed between your thighs.",

	Screen_Sub = "You shift on the bedroll. Not much. Just enough to make space. The invitation sits in the silence, louder than words.\n\n%man% exhales. The tension drains out of him and something hungrier takes its place. He closes the distance on hands and knees, settling beside you with a confidence that makes your pulse jump. His hand finds your hip in the dark, and you feel the heat of him through the thin fabric like a brand.\n\nHe doesn't rush. That surprises you. His fingers trace the shape of you slowly, learning the geography of your body through layers of cloth, and when he finally leans in to press his lips against the curve of your neck, the sound you make is small and involuntary and entirely his.\n\nThe rest happens in fragments. The rustle of clothing. The weight of him above you. His breath ragged against your throat as he takes what you've offered, and your fingers twisted in the blanket because you cannot bring yourself to push him away. You don't want to. That's the part that burns.\n\nAfterward, he lies beside you in the quiet. His hand rests on your stomach, proprietary and warm. You stare at the canvas ceiling and feel the ache of what just happened settle into your bones.\n\n%SPEECH_ON%This stays between us.%SPEECH_OFF%Your voice is steadier than you feel.\n\nHe presses his lips against your temple.%SPEECH_ON%Whatever you say, captain.%SPEECH_OFF%But you both know that's not how secrets work in a company of mercenaries.",

	Screen_DomSuccess = "You sit up in one fluid motion and put your hand flat against his chest. He opens his mouth to speak and you push, hard, sending him onto his back on the bedroll.\n\n%SPEECH_ON%You came to my tent.%SPEECH_OFF%You swing a leg over him, settling your weight across his hips. His hands come up to grab you and you catch them, pinning his wrists beside his head with a grip that makes him gasp.%SPEECH_ON%That means we play by my rules.%SPEECH_OFF%Whatever he was expecting, this wasn't it. His eyes are wide in the moonlight, his body taut as a drawn bow beneath you. You can feel every ridge and line of him, can feel exactly how much he wants this despite the shock on his face.\n\nYou take your time. You make him wait. When you finally give him what he came for, it is on your terms, at your pace, and by the end he is gasping your name like a prayer into the dark.\n\nAfter, you roll off him and point at the tent flap.\n\n%SPEECH_ON%Now get out.%SPEECH_OFF%He goes. Wobbly. Dazed. Thoroughly, comprehensively yours.",

	Screen_DomFail = "You sit up and push your hand against his chest, trying to drive him back. For a moment he shifts, surprised, and you press the advantage, swinging over him.\n\nHis reflexes are quicker than yours in the dark. He catches your hip, twists, and suddenly you're the one on your back with his weight settling over you.\n\n%SPEECH_ON%Nice try.%SPEECH_OFF%His voice is thick with something between amusement and desire. His hands find your wrists with a sureness that makes your stomach flip, pinning them above your head.\n\nYou strain against his grip. Testing. His fingers tighten. The last coherent thought you manage is that you should be angry. Should be. But the heat pooling low in your belly doesn't feel like anger, and the small, breathless sound that escapes you doesn't sound like protest.\n\nHe takes that sound for what it is. The rest unfolds with the kind of inevitability that happens when you've already lost and your body knows it before your pride does. He isn't rough, but he isn't gentle either, and when he finally lets go of your wrists your hands go to his shoulders instead of the tent flap.\n\nAfterward, he stays. You want to tell him to leave but the words won't form. His arm curls around your waist, pulling you against his chest, and you hate how easily you fit there.",
};

// =============================================================================
// ETHEREAL PROGRESSION — Foreshadowing events leading to the gheist encounter.
// =============================================================================

// ---- The Threshold (60 combined climaxes, signals gheist encounter is near) ----
// =============================================================================
// COURTESAN ORIGIN — Intro event sequence fired on campaign start.
// =============================================================================

::Lewd.Strings.CourtesanIntro <- {
	Screen_A = "You wake in a bed that is not yours, in a room that smells of wine and sandalwood and the particular staleness of a night that went on too long. Silk sheets pool around your waist. The man beside you is still sleeping, one arm thrown across the pillow where your head was, fingers curled loosely around the memory of your hair.\n\nYou do not remember his name. You remember his title, because titles are what matter in this world, and you remember the way he introduced you to his guests at dinner: my jewel, my treasure, as though you were a brooch he had pinned to his lapel for the evening. You remember the laughter and the wine and the way his hand rested on the small of your back, steering you between conversations like a ship between harbors. You remember what came after, because you always remember what comes after, even when you would rather not.\n\nThe ceiling is painted with a hunting scene. Hounds chasing a fox through golden wheat. You have stared at this ceiling before, or one very like it, in a different estate, beneath a different nobleman, counting brushstrokes until the grunting stopped. The foxes never escape in these paintings.",

	Screen_B = "You dress in the grey light before dawn, moving quietly so as not to wake him. Your clothes are where he tossed them, draped across a chair with the carelessness of a man who did not have to fold them himself. You catch your reflection in the dressing mirror as you lace your bodice: a face that has been called beautiful by men who wanted something from it, hair that has been stroked by fingers that never asked permission, a body that has been passed between noble houses like a vintage bottle, each lord taking his pour before sending you on to the next.\n\nThrough the window, the road below the estate is already busy with the morning's traffic. A merchant caravan rattles past, followed by a column of sellswords in mismatched armor, their captain riding at the head with a banner you do not recognize. They move with the easy confidence of people who belong to no one. Who sell their strength on their own terms and walk away when the contract is done.\n\nYou watch them until they disappear around a bend in the road, and the feeling that settles in your chest is not envy. It is recognition. They sell their bodies too, just differently. But at the end of the day the swords go back in the sheaths and the soldiers go where they please, and no one steers them between conversations with a hand on the small of their back.",

	Screen_C = "You take what you can carry. A handful of coins from the nightstand, because he will not miss them and you will need to eat. A short blade from the writing desk, ornamental but sharp enough. The clothes on your back and the skills in your head, which are considerable if unconventional.\n\nThe household is still sleeping when you slip through the servants' entrance. The morning air hits your face like cold water and you stand on the cobblestones for a long moment, breathing, because you realize with a sudden vertigo that you have never been alone before. There has always been a lord or a patron or a handler, someone whose name you wore like a collar, someone who decided where you slept and with whom.\n\nThe road stretches in both directions. You do not know where it leads. You do not know how to fight, not really, not the way the sellswords you watched from the window do. You know how to read a room, how to make a man feel powerful, how to survive a night by becoming whatever the person paying for your company needs you to be.\n\nIt will have to be enough. You pick a direction and start walking, heels clicking on the road, and the sound echoes off the estate walls behind you like the first line of a story that no one else is writing.",
};

// =============================================================================
// DAJI DREAM EVENTS — Post-ethereal conversations that unlock clothing recipes.
// Daji is the fox spirit who merged with the PC. Dom-natured, encourages dominance.
// =============================================================================

// ---- Corset Dream: Daji's first clear conversation, reveals her name ----
::Lewd.Strings.DajiCorset <- {
	Screen_A = "You dream of a room with no doors.\n\nThe walls are dark lacquer, polished until they hold light the way still water holds the moon. Jasmine thickens the air, layered over amber and something animal, something that belongs to a body curled too long in warm sheets. You are naked and the nakedness feels honest, as though this is the one place where clothing would be a lie.\n\nYour reflection watches you from the lacquer. It matches your posture but not your expression, and when you tilt your head the reflection's fox-gold eyes hold steady, amused, waiting for you to notice the difference. A tail sways behind the glass where your own body casts none. You have seen those eyes before, in glimpses and peripheral flickers since the gheist's spirit settled into your bones, but tonight they are patient and unhurried in a way that makes your stomach tighten with recognition.\n\nPressure builds around your ribs. Not hands, not rope. Something precise and architectural, like the memory of a garment you have never worn. It follows the curve of your body with an intimacy that belongs to the thing looking out through your reflection, and when a voice rises in your chest it takes a moment to realize the voice is not entirely yours.%SPEECH_ON%You feel that? That tightness. You have been walking around without it and it shows.%SPEECH_OFF%The reflection smiles with your mouth. The name surfaces the way a dreamer remembers a word from a language she spoke in another life, arriving whole and unannounced, simply there: Daji.",

	Screen_Dom = "The pressure around your ribs sharpens into definition, stays and boning drawing your posture into something deliberate, and the part of you that is Daji hums with approval at the way your shoulders settle back without being told. The voice in your chest carries a warmth that feels less like affection and more like the satisfaction of watching a blade finally hold its edge.%SPEECH_ON%There it is. You already stand like someone who expects to be obeyed, but your body does not match the promise. All that authority, and you let them see you breathe ragged after a march. You let the weight of the day round your shoulders. They forgive it because they fear you, but forgiveness and respect are not the same animal.%SPEECH_OFF%In the lacquer reflection Daji's tail flicks once, a punctuation mark. The phantom garment tightens and you feel your lungs fill against resistance, each breath becoming something earned rather than given. Your spine lengthens and the change ripples outward through your bearing until you can feel the difference in how you hold your own gaze in the mirror.%SPEECH_ON%Serpent skin for the shell. Gossamer against the skin so it breathes. Lindwurm bone for the stays, because nothing else holds its shape against a body like yours. Find a tailor who has worked with dragonskin and does not ask questions.%SPEECH_OFF%The design presses itself into your awareness the way a brand presses into leather, every seam and lacing eyelet rendered in pressure and heat along your skin. The reflection watches you absorb it, her expression settling into something close to pride.",

	Screen_Sub = "The pressure around your ribs tightens past comfort and the breath you draw comes shallow, rationed, controlled by something that is not you. Your pulse quickens and the quickening brings heat, a flush that spreads from your sternum outward until your skin prickles against the phantom boning. The part of you that is Daji feels the response and leans into it, the way a hand tightens on a leash when the leash pulls back.%SPEECH_ON%I felt you the moment I settled in. All that strength, and what you wanted most was something to push against. Someone to tell you when to breathe.%SPEECH_OFF%The phantom corset draws one notch tighter and your ribs ache with the kind of ache that lives on the border of something else, something your body recognizes as want. In the lacquer reflection Daji's eyes are half-lidded and possessive, watching the way your chest rises and falls in the rhythm she has set.%SPEECH_ON%Serpent skin. Gossamer lining, because I want you to feel it against your skin and think of me. Lindwurm bone for the stays. When you wear it every breath will press against something that does not give, and you will know that I am the one who is not giving.%SPEECH_OFF%Her voice drops lower, resonating in the cage of your chest, vibrating against the phantom stays.%SPEECH_ON%Build it. Wear it. And every time it squeezes, say my name, even if only inside your own head.%SPEECH_OFF%Your lips shape the word without being told. Daji. The satisfaction that floods through you is not yours, but the pleasure of satisfying her curls warm and heavy in your belly all the same.",

	Screen_Wake = "You surface from sleep with your arms folded tight across your ribs, fingers pressing into the gaps between bones as though searching for stays that are not there yet. The room smells of jasmine and your skin is flushed, though the morning air is cool.\n\nThe design remains, sharp as an architectural drawing: every seam, every eyelet, the precise curvature of lindwurm bone stays shaped to the negative space of your body. You could sketch it with your eyes closed. The knowledge sits in your hands and along your ribcage where the phantom pressure still lingers.\n\nA name threads through the dregs of sleep, settling into the part of your mind that used to be empty and is now occupied. Daji. She does not speak again this morning, but the awareness of her presence has changed, resolving from a vague warmth into something with edges and opinions and a tail that flickers in your peripheral thoughts when she finds something amusing.",
};

// ---- Hazeem Chains: Letter from Hazeem describes piercing chains, PC craves the degradation ----
::Lewd.Strings.HazeemChains <- {
	Screen_A = "A messenger finds your camp at dusk, a lean southern boy in dusty travelling clothes who asks for you by name and presses a sealed letter into your hands before vanishing back down the road without waiting for a reply. The seal is crimson wax stamped with a serpent coiled around a crescent moon, and you recognize it before you break it. Hazeem.\n\nYou carry the letter to your tent and sit with it on your bedroll, turning it over in your hands. The parchment is heavy and expensive, scented faintly with myrrh, and when you unfold it the handwriting is precise and unhurried, the script of a man who writes the way he speaks: with the assumption that you will read every word.\n\n%SPEECH_ON%My jewel. Word reaches me that you still wander the north with your sellswords, wearing my gifts against your skin. I think of you often. I think of the sounds you made and the way your body answered before your mind could object. I have been designing something new for you and I find I cannot wait to describe it.%SPEECH_OFF%",

	// Tier 2 variant: nose + lip ring + nipple piercings (rings, not plugs)
	Screen_B_T2 = "You read on. His handwriting does not waver, each letter formed with the patience of a man who enjoys the act of describing what he will do to you.\n\n%SPEECH_ON%Chains, my jewel. Fine gold links forged from ancient coins, weighted at the junctions with cut gems so they hang with purpose rather than merely drape. A chain from your nose ring to your lip ring, short enough to pull taut when you open your mouth too wide, reminding you to speak softly or not at all. Longer chains threaded through your nipple piercings, looping between your breasts and crossing beneath them, catching on armor and swinging with every stride so that each step you take tugs at the tender flesh I marked for you.\n\nThey are not decorative. A woman wearing these cannot fight properly. The chains catch and pull. They distract. Every sudden movement becomes a punishment, and every punishment becomes a pleasure, because that is what you are. You would be slower, weaker, less useful to your company in every way that matters on a battlefield. The constant stimulation would keep you aching and wet and unable to think about anything except the next tug, the next pull, the next reminder that your body is not your own.\n\nMost women would burn this letter. But you are not most women, are you, jewel? I suspect you are already wet just reading this. I suspect your hand has drifted somewhere it should not be and your breath has gone shallow and your body has already decided for you, the way it always does.%SPEECH_OFF%You set the letter down on your bedroll. Your hands are trembling and your face is flushed and he is right about all of it. You felt the heat build with every line, each described degradation stoking something low and liquid in your belly that stopped pretending to be anything other than hunger a long time ago. Slower, weaker, less effective. The words should repulse you. Instead they sit in your chest like coals, and the ache between your legs makes it difficult to keep reading with both hands above the blanket.",

	// Tier 3 variant: nose + lip ring + nipple plugs (heavy ornaments)
	Screen_B_T3 = "You read on. His handwriting does not waver, each letter formed with the patience of a man who enjoys the act of describing what he will do to you.\n\n%SPEECH_ON%Chains, my jewel. Fine gold links forged from ancient coins, weighted at the junctions with cut gems so they hang with purpose rather than merely drape. A chain from your nose ring to your lip ring, short enough to pull taut when you open your mouth too wide, reminding you to speak softly or not at all. Longer chains hanging from the plugs in your nipples, weighted by the gems already seated inside you, crossing between your breasts and catching on armor so that every stride swings them and every swing pulls at flesh that has learned to translate pain into something wetter and more honest.\n\nThey are not decorative. A woman wearing these cannot fight properly. The chains catch and pull. They distract. Every sudden movement becomes a punishment, and every punishment becomes a pleasure, because that is what you are. You would be slower, weaker, less useful to your company in every way that matters on a battlefield. The constant stimulation would keep you aching and wet and unable to think about anything except the next tug, the next pull, the next reminder that your body is not your own.\n\nMost women would burn this letter. But you are not most women, are you, jewel? I suspect you are already wet just reading this. I suspect your hand has drifted somewhere it should not be and your breath has gone shallow and your body has already decided for you, the way it always does.%SPEECH_OFF%You set the letter down on your bedroll. Your hands are trembling and your face is flushed and he is right about all of it. You felt the heat build with every line, each described degradation stoking something low and liquid in your belly that stopped pretending to be anything other than hunger a long time ago. Slower, weaker, less effective. The words should repulse you. Instead they sit in your chest like coals, and the ache between your legs makes it difficult to keep reading with both hands above the blanket.",

	Screen_C = "The final passage is shorter, written in a hand that seems almost amused.\n\n%SPEECH_ON%I will not make them for you. That is not the point. The point is that you will seek out the gold and the gems yourself. You will find a craftsman and describe to a stranger, in detail, the chains you want hung from your own body. Every moment of that process will be you choosing this. Not because I commanded it. Because you cannot stop wanting it.\n\nI look forward to seeing you in them.%SPEECH_OFF%You fold the letter carefully and press it flat beneath your bedroll where no one will find it. The design he described is vivid in your mind, rendered in the precise language of a man who understands exactly what he is doing to you from a thousand miles away: every link, every gem, the specific weight and tension of chains calibrated to turn a warrior into an ornament.\n\nYou should burn the letter. You should be angry at what he wrote. You should feel the insult in being told you would be made slower, weaker, reduced to a distraction from your own command.\n\nInstead you lie back on your bedroll with your fingers curled against your palms, itching for gold and gemstone, and the only thought left in your head is how quickly you can find what you need.",
};

// ---- Silk Reflection: PC designs bodysuit + fishnets from Qingde's aesthetic ----
::Lewd.Strings.SilkReflection <- {
	Screen_A = "You notice it at a market stall in a town whose name you have already forgotten.\n\nThe merchant is spreading bolts of fabric across a trestle table for a woman haggling over curtain material, and among the linens and rough-spun wool there is a single bolt of something finer. Gossamer, probably. Spider silk combed until it shines like wet glass. The merchant handles it carelessly, bunching it between thick fingers, and you feel an odd prickle of irritation at the way he treats it.\n\nYou have been noticing fabric for weeks now, though you could not have said when it started. Running your thumb along tent canvas and cataloguing the weave. Watching the way firelight changes the color of a cloak thrown over a sleeping brother's shoulders. Testing the weight of a scarf at a trader's cart and holding it up to the lamp to see how much light passes through. Small, absent habits that meant nothing until this moment when they suddenly arrange themselves into a pattern you should have recognized sooner.\n\nThe memory arrives without invitation: Qingde's servants in their dark blue silk, the way the fabric shifted against their bodies when they moved, how the lamplight inside the palanquin turned the weave translucent in places where it stretched across a shoulder or a forearm. You had not been paying attention to the silk at the time. You were paying attention to other things. But your hands remember what your mind did not bother to record, and now your fingers itch with the knowledge of how gossamer would drape against skin that has become softer and more sensitive than any sellsword's skin has a right to be.",

	Screen_B = "You buy the bolt of gossamer without haggling and carry it back to camp under your arm. %randombrother% raises an eyebrow as you pass but says nothing, which is wise of him.\n\nInside your tent you spread the fabric across your bedroll and sit with it for a long time. Your fingers work without consulting you, pinching seams, folding edges, holding sections against your forearm and tilting them toward the lantern to watch the way light moves through the weave. Two shapes begin to emerge from the folding and refolding, as distinct as if someone had drawn them for you.\n\nThe first is a bodysuit cut to follow every line from collarbone to hip, sheer enough that the skin beneath would glow through the weave like lamplight through rice paper. It would conceal nothing and protect less, but the act of wearing it would transform nakedness from vulnerability into something deliberate and chosen. Gossamer against bare skin, warm as breath, moving when you move.\n\nThe second is simpler and stranger: a net-weave for the legs, diamond-patterned, designed to complement the architecture of heels by drawing the eye along the calf and thigh in a lattice that makes bare skin look like something glimpsed through a window. The pattern reminds you of the lattice screens in the palanquin, designed to let you see out without letting others see in, except inverted. This is a screen that lets them see everything while pretending to cover it.\n\nYou sit back and look at what your hands have sketched in fabric and fold. Nobody asked you to make these. Nobody whispered the idea in your ear or offered gold for your compliance. This came from a place inside you that has been quietly rearranging itself since the first time you stepped into Qingde's world and let his servants undress you, and the realization settles into your stomach with a weight that is not quite shame and not quite pride but lives in the warm space between them.",
};

// ---- Harness Dream: Daji pushes toward dominance, weaponizing desire ----
::Lewd.Strings.DajiHarness <- {
	Screen_A = "The lacquer room is waiting when you close your eyes, familiar now the way a second home becomes familiar, and Daji's reflection greets you with the lazy half-smile of someone who has been thinking all day and finally has you alone to share it.\n\nThe phantom corset is absent tonight. In its place you feel something different taking shape across your skin: straps looping over your shoulders and beneath the curve of your breasts, crossing between your shoulder blades, tracing lines down your stomach that frame rather than conceal. Where the corset held you in, this pulls you open. Every strap is a line drawn on a map that says %italicS%look here%italicE%, and the arrangement leaves more skin bare than it covers.\n\nIn the lacquer your reflection turns, and the harness moves with it like a living thing, tightening where the body curves and loosening where it straightens, drawing the eye along paths that have nothing to do with modesty. Daji's tail sways behind the glass with a slow, predatory rhythm.%SPEECH_ON%The corset was for you. What I am showing you now is for them.%SPEECH_OFF%",

	Screen_Dom = "The straps settle against your skin with the weight of intention, and you feel Daji's awareness sharpen to a point behind your eyes as she watches you study the harness in the lacquer. Your posture shifts without conscious effort, shoulders drawing back, chin lifting, and the straps respond by framing the new geometry of your confidence the way a setting frames a jewel.%SPEECH_ON%You have noticed how they look at you. How their hands falter mid-swing when you cross their line of sight. How the ones with discipline pretend not to stare and the ones without it forget they are holding swords. You have been treating that as a side effect. I am telling you it is the sharpest weapon in your arsenal.%SPEECH_OFF%In the reflection Daji traces a strap across her collarbone with one claw-tipped finger, and you feel the ghost of it on your own skin, a line of heat that makes the nerve endings beneath it sing.%SPEECH_ON%Demon alp skin. You know what alps do, what they feed on. The hide still carries the residue of every desire they ever drank. Wear it against your body and that hunger becomes yours to direct. Let them look. Let them want. And when the wanting makes their guard drop and their resolve crumble, let them understand that the ache in their chest is a weapon and you are the one holding it.%SPEECH_OFF%The phantom harness tightens once across your shoulders, a feeling like hands settling on your collarbones from behind, and the part of you that is Daji radiates a fierce, sharp-edged satisfaction that tastes like victory before a battle has even begun. You feel the design burning into your skin: every buckle and ring, the specific tension of each strap, the way the alp-leather would warm against you until the boundary between skin and hide stopped mattering.",

	Screen_Sub = "The straps tighten across your chest and you feel your breath catch, though not from constriction. The harness does not compress the way the corset does. Instead it frames, it displays, and the vulnerability of being so deliberately arranged makes heat pool low in your belly before Daji has even spoken. Her voice rises in your chest with the unhurried confidence of someone who knows exactly how this conversation will end.%SPEECH_ON%I cannot walk out there in your skin. I cannot stand in front of them and watch their knees buckle the way they did when I was alive. But you can.%SPEECH_OFF%The reflection's fox-gold eyes burn brighter, and you feel the hunger behind them like a hand pressed flat against your sternum from the inside.%SPEECH_ON%When I was whole I could empty a room with my presence alone. Men forgot their own names. Women forgot their anger. I fed on the wanting the way fire feeds on air, and I was never, ever full.%SPEECH_OFF%A strap tightens between your shoulder blades and your back arches involuntarily, pushing your chest forward into the frame the harness has made of your body. In the lacquer your reflection is beautiful in a way that aches, and Daji's possessive satisfaction hums through every nerve.%SPEECH_ON%Demon alp skin for the straps, because it still carries the memory of swallowed desire. Wear it for me. Walk among them wearing my appetite on your skin and let them drown in what they cannot have. Every time one of them loses focus, every time a blade goes wide because the creature holding it forgot how to think, that is my hand reaching through yours.%SPEECH_OFF%The phantom harness pulses once, warm as a heartbeat, and you understand that this is not a gift or a suggestion. It is a leash made of purpose, offered by the thing inside you that is too vast to fit in your body alone and needs you to carry the overflow into the world.",

	Screen_Wake = "You wake on your back with your hands resting on your collarbones, fingertips tracing the lines where phantom straps settled against your skin. The impression fades slowly, reluctantly, as though the dream wants to leave its mark on the waking world.\n\nThe design is sharper than the corset's was, leaner and more deliberate, and it carries with it the faint memory of alps and the sweet, cloying scent of stolen desire. Demon alp skin for the straps, masterwork fabric where the hide would rest against bare skin. You know this the way you knew the corset: whole, unlearned, placed in your mind by hands that are not entirely yours.\n\nDaji stirs in the back of your awareness, warm and expectant and hungrier than usual. You can feel her impatience the way you feel your own pulse, a constant rhythm urging you forward, forward, toward something she lost centuries ago and intends to taste again through you.",
};

::Lewd.Strings.EtherealReady <- {
	Screen_A = "You dream of graves.\n\nNot the shallow pits the company digs after battle, but old ones. Stone markers worn smooth by centuries of rain, leaning at angles in soil that has long since forgotten what it holds. The air tastes of wet earth and something sweeter underneath, like perfume left in an empty room.\n\nYou walk among the headstones and you are not afraid. The presence that has haunted your periphery for weeks walks beside you now, close enough that your shoulders almost touch. You cannot see her, but you know her shape the way you know the weight of your own sword. She is tall. She is old. She wants something that is buried here.\n\n%SPEECH_ON%Find me.%SPEECH_OFF%You wake with dirt under your fingernails and the taste of graveyard soil on your tongue.\n\nThe pull does not fade with daylight. As the company breaks camp and takes to the road, you find your eyes drawn to every cemetery you pass, every crumbling ruin half-swallowed by forest. The dead places call to you with a voice you feel in your sternum rather than hear. Something is waiting among the graves and the restless spirits. Something that has been waiting for a very long time, and now knows you are ready to find it.\n\n%randombrother% falls into step beside you and says something about the road ahead. You nod without hearing. Your attention is elsewhere, pulled toward a horizon you cannot name, following a thread of jasmine and old death that only you can smell.",
};
